# Generated by Django 6.0 on 2025-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_slug_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Backend_implementation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Frontend_implementation',
            field=models.TextField(blank=True),
        ),
    ]
