# Generated by Django 6.0 on 2025-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_backend_implementation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Backend_implementation',
            new_name='backend_implementation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Frontend_implementation',
            new_name='frontend_implementation',
        ),
        migrations.AddField(
            model_name='project',
            name='why_this_application',
            field=models.TextField(blank=True),
        ),
    ]
